version: 2.1
orbs:
  node: circleci/node@5.0.2
  eb: circleci/aws-elastic-beanstalk@2.0.1
  aws-cli: circleci/aws-cli@3.1.1

jobs:
  build:
    docker:
      - image: "cimg/node:14.15"
    steps:
      # install node and checkout code
      - node/install:
          node-version: '14.15'      
      - checkout
      - aws-cli/setup
      - eb/setup
      - run:
          name: Install frontend modules
          command: npm run frontend:install
      - run:
          name: lingting frontend
          command: npm run frontend:lint
      - run:
          name: build frontend files
          command: npm run frontend:build
      - persist_to_workspace:
          root: udagram/udagram-frontend
          paths:
            - www

  deploy:
    docker:
      - image: "cimg/base:stable"
    steps:
      - node/install:
          node-version: '14.15'
      - checkout
      - eb/setup
      - aws-cli/setup
      - attach_workspace:
          at: /tmp/www
      - run:
          name: check artifacts
          command: |
            ls /tmp/www/*
      - run:
          name: deploy frontend
          command: |
            ls /tmp/www
            npm run frontend:deploy
            
workflows:
  udagram:
    jobs:
      - build
      - deploy:
          requires:
            - build
